const PRODUCTS=[
 {id:'autocad-2024',name:'AutoCAD 2024',cat:'cad',label:'CAD',accent:'#e73b4d',desc:'2D and 3D CAD design and drafting service.',features:['Product selection: AutoCAD 2024','Engineering and drafting workflow','Technical support route available']},
 {id:'autocad-2025',name:'AutoCAD 2025',cat:'cad',label:'CAD',accent:'#d42b41',desc:'CAD design and drafting service for professional workflows.',features:['Product selection: AutoCAD 2025','2D and 3D design workflow','Technical support route available']},
 {id:'autocad-2027',name:'AutoCAD 2027',cat:'cad',label:'CAD',accent:'#e54a56',desc:'Current-generation CAD workflow option in the Techies Lab collection.',features:['Product selection: AutoCAD 2027','Engineering and design workflow','Technical support route available']},
 {id:'electrical-2024',name:'AutoCAD Electrical 2024',cat:'electrical',label:'ELEC',accent:'#f05a3f',desc:'Electrical design workflow for schematic and control-system projects.',features:['Product selection: AutoCAD Electrical 2024','Electrical engineering workflow','Technical support route available']},
 {id:'electrical-2026',name:'AutoCAD Electrical 2026',cat:'electrical',label:'ELEC',accent:'#ff7a34',desc:'Electrical design workflow for engineering documentation and projects.',features:['Product selection: AutoCAD Electrical 2026','Electrical engineering workflow','Technical support route available']},
 {id:'architecture-2024',name:'AutoCAD Architecture 2024',cat:'architecture',label:'ARCH',accent:'#8d4ed7',desc:'Architecture-focused drafting and design workflow.',features:['Product selection: AutoCAD Architecture 2024','Architectural drafting workflow','Technical support route available']},
 {id:'mep-2024',name:'AutoCAD MEP 2024',cat:'engineering',label:'MEP',accent:'#1a9f7c',desc:'Mechanical, electrical and plumbing design workflow.',features:['Product selection: AutoCAD MEP 2024','MEP engineering workflow','Technical support route available']},
 {id:'nastran-2025',name:'AutoCAD Inventor Nastran 2025',cat:'engineering',label:'NAS',accent:'#b45a1c',desc:'Engineering analysis and simulation workflow selection.',features:['Product selection: AutoCAD Inventor Nastran 2025','Engineering analysis workflow','Technical support route available']}
];
let activeFilter='all', selected=null;
const grid=document.getElementById('productGrid');
function badge(p,large=false){return `<div class="${large?'modal-badge':'product-badge'}" style="--accent:${p.accent}"><div>${p.name.startsWith('AutoCAD Electrical')?'A/E':p.name.startsWith('AutoCAD Architecture')?'A/A':p.name.startsWith('AutoCAD MEP')?'MEP':p.name.includes('Nastran')?'N':p.name.startsWith('AutoCAD')?'A':'A'}<small>${p.label}</small></div></div>`}
function render(){const q=document.getElementById('searchInput').value.toLowerCase();grid.innerHTML=PRODUCTS.filter(p=>(activeFilter==='all'||p.cat===activeFilter)&&p.name.toLowerCase().includes(q)).map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-visual">${badge(p)}</div><div class="product-body"><span class="product-category">${p.cat.toUpperCase()}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><div class="price">$5.00 USD</div><div class="card-actions"><button class="info-btn" data-info="${p.id}">INFORMATION</button><button class="order-btn" data-order="${p.id}">ORDER NOW</button></div></div></div></article>`).join('')||'<div class="empty-order">No matching software found.</div>'}
render();
document.getElementById('searchInput').addEventListener('input',render);
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');activeFilter=b.dataset.filter;render()}));
grid.addEventListener('click',e=>{const id=e.target.dataset.info||e.target.dataset.order;if(!id)return;const p=PRODUCTS.find(x=>x.id===id);if(e.target.dataset.info)openInfo(p);else selectProduct(p)});
const modal=document.getElementById('infoModal');
function openInfo(p){selected=p;document.getElementById('modalBadge').outerHTML=badge(p,true).replace('class="modal-badge"','class="modal-badge" id="modalBadge"');document.getElementById('modalCategory').textContent=p.cat.toUpperCase();document.getElementById('modalTitle').textContent=p.name;document.getElementById('modalDescription').textContent=p.desc;document.getElementById('modalFeatures').innerHTML=p.features.map(x=>`<li>${x}</li>`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeInfo(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.getElementById('closeModal').onclick=closeInfo;modal.addEventListener('click',e=>{if(e.target===modal)closeInfo()});
document.getElementById('modalOrderBtn').onclick=()=>{if(selected)selectProduct(selected);closeInfo()};
function selectProduct(p){selected=p;document.getElementById('emptyOrder').hidden=true;document.getElementById('orderDetails').hidden=false;document.getElementById('selectedProductName').textContent=p.name;document.getElementById('selectedProductCategory').textContent=p.cat.toUpperCase()+' SOFTWARE SERVICE';updateTotal();document.getElementById('payment').scrollIntoView({behavior:'smooth',block:'start'})}
function updateTotal(){const total=5+(document.getElementById('remoteInstallation').checked?10:0);document.getElementById('totalPrice').textContent='$'+total.toFixed(2)}document.getElementById('remoteInstallation').addEventListener('change',updateTotal);document.getElementById('clearOrder').onclick=()=>{selected=null;document.getElementById('emptyOrder').hidden=false;document.getElementById('orderDetails').hidden=true};
document.querySelectorAll('input[name="paymentMethod"]').forEach(r=>r.addEventListener('change',()=>{const bank=r.value==='bank'&&r.checked;document.getElementById('bankDetails').hidden=!bank;document.getElementById('onlineDetails').hidden=bank}));
function validDetails(){if(!selected){alert('Please select a software product first.');return false}const form=document.getElementById('orderForm');if(!form.reportValidity())return false;return true}
document.getElementById('bankPaymentBtn').onclick=()=>{if(!validDetails())return;const ref=document.getElementById('transactionRef').value.trim();if(!ref){alert('Please enter your payment reference / transaction ID.');return}const remote=document.getElementById('remoteInstallation').checked?'Yes (+$10)':'No';const total=document.getElementById('remoteInstallation').checked?'$15.00':'$5.00';const msg=`Hello Techies Lab.%0A%0AI have made a bank transfer for my order.%0A%0AProduct: ${encodeURIComponent(selected.name)}%0ARemote Installation: ${remote}%0ATotal: ${total}%0AName: ${encodeURIComponent(document.getElementById('customerName').value)}%0AEmail: ${encodeURIComponent(document.getElementById('customerEmail').value)}%0ACountry: ${encodeURIComponent(document.getElementById('customerCountry').value)}%0ATransaction Reference: ${encodeURIComponent(ref)}%0A%0APlease find my payment confirmation attached.`;window.open('https://wa.me/2349071766222?text='+msg,'_blank')};
const PAYSTACK_PUBLIC_KEY='pk_live_79b8a2a9c30b91528bb0d9866601a1e7181fff13';
document.getElementById('orderForm').addEventListener('submit',e=>{e.preventDefault();if(!validDetails())return;const total=document.getElementById('remoteInstallation').checked?15:5;const name=document.getElementById('customerName').value.trim();const email=document.getElementById('customerEmail').value.trim();const country=document.getElementById('customerCountry').value.trim();const phone=document.getElementById('customerWhatsapp').value.trim();if(typeof PaystackPop==='undefined'){alert('Secure checkout could not load. Please check your internet connection and try again.');return}const ref='TL-'+Date.now();const handler=PaystackPop.setup({key:PAYSTACK_PUBLIC_KEY,email,amount:Math.round(total*100),currency:'USD',ref,metadata:{custom_fields:[{display_name:'Customer Name',variable_name:'customer_name',value:name},{display_name:'Country',variable_name:'country',value:country},{display_name:'WhatsApp',variable_name:'whatsapp',value:phone},{display_name:'Selected Product',variable_name:'selected_product',value:selected.name},{display_name:'Remote Installation',variable_name:'remote_installation',value:document.getElementById('remoteInstallation').checked?'Yes':'No'}]},callback:function(response){const params=new URLSearchParams({ref:response.reference,product:selected.name,total:'$'+total.toFixed(2),remote:document.getElementById('remoteInstallation').checked?'Yes':'No',name:name,email:email});window.location.href='thank-you.html?'+params.toString()},onClose:function(){}});handler.openIframe()});
document.getElementById('year').textContent=new Date().getFullYear();
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav-links');menu.onclick=()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};
